console.log("!Array Time! First let's create an array like this:");
let coolArray = [1,3,4,6,8,2];
console.log();
console.log("To create a variable for the length of coolArray we will use the .length operator:");
let length = coolArray.length;
console.log();
console.log("To find value at first index (spot), know that the computer counts arrays starting at 0, not 1")
console.log("So see that this code gives... " + coolArray[0] + ", which is giving you the first value in coolArray");
console.log();
console.log("To find the value at the second index... " + coolArray[1]);
console.log();
console.log("To find the last index in coolArray..." + coolArray[coolArray.length-1]);
console.log();
console.log("To specify an index to find using a variable:");
let k = 4;
console.log("To find index k, you need to factor in that index count starts from 0... " + coolArray[k-1]);
console.log();
console.log("If we wanted to append a new number (9), use the .push command:");
coolArray.push(9);
console.log("After that, CoolArray now contains 9 in the last index..." + coolArray);
console.log();
console.log("If we want to remove the last element of coolArray, use the splice command");
console.log("Specify which index the removal starts at and how many values it will remove:");
coolArray.splice(coolArray.length-1,1);
console.log("Here is how coolArray looks now... " + coolArray);
console.log();
console.log("Now let's use splice to add a new element 345 at the beginning of cool array");
console.log("Specify 1) where we want to add 2) how many we want to replace (if any) and 3) what we want to add:");
coolArray.splice(0,0,345);
console.log("After prepending the number 345, now coolArray now looks like this... " + coolArray);
console.log();
console.log("Now, let's remove 345 using splice, specifying the index and how many elements we want to remove:");
coolArray.splice(0,1);
console.log("So now coolArray again looks like... " + coolArray + " without 345 in its front");
console.log();
console.log("Now we are done learning about Arrays!");
